trigger:
  branches:
    include:
      - main

pr: 
  branches:
    include:
      - main

pool:
  name: MySelfHostedPool

variables:
  resourceGroupName: "myResourceGroup"
  serviceConnection: "myARMConnection"
  subscriptionId: "938d8cb0-7326-4b21-82ac-a9a5017a87ea"
  location: "East US"

stages:
- stage: Deploy_Infra
  displayName: "Deploy Storage Accounts & Linux VM"
  jobs:
  - job: Deploy_Azure_Infra
    displayName: "Deploy ARM Templates"
    steps:

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Storage Accounts
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: 'storageAccounts.json'
        deploymentMode: 'Incremental'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Linux Machine
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: 'myLinuxVM.json'
        deploymentMode: 'Incremental'
        overrideParameters: "- sshPublicKey $(cat ~/.ssh/id_rsa.pub)"
