trigger:
  branches:
    include:
      - master

pool:
  name: MySelfHostedPool

variables:
  resourceGroupName: "myResourceGroup"
  serviceConnection: "myARMConnection"
  subscriptionId: "938d8cb0-7326-4b21-82ac-a9a5017a87ea"
  location: "East US"
  sshKeyPath: "$(Build.ArtifactStagingDirectory)/id_rsa"
  keyVaultName: "myPresonalKeyVault"
  vaultAdmin: "Guy Erreich"

stages:
- stage: Generate_SSH_Key
  displayName: "Generate SSH Key"
  jobs:
  - job: GenerateKey
    displayName: "Generate SSH Key and Store Public Key"
    steps:
    - script: |
        ssh-keygen -t rsa -b 2048 -f $(sshKeyPath) -C "azureuser@myserver" -m PEM -N "" -q
        sshPublicKey=$(<$(sshKeyPath).pub)
        sshPrivateKey=$(<$(sshKeyPath))
        echo "##vso[task.setvariable variable=sshPublicKey;isOutput=true;isSecret=true]$sshPublicKey"
        echo "##vso[task.setvariable variable=sshPrivateKey;isOutput=true;isSecret=true]$sshPrivateKey"
      displayName: "Generate SSH Key"
      name: generateKey

    - task: AzureCLI@2
      displayName: "Get User Object ID"
      name: getAdminObjectID
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          userId=$(az ad user list --display-name "$(vaultAdmin)" --query "[].id" --output tsv)
          echo "Fetched User Object ID: $userId"
          echo "##vso[task.setvariable variable=adminObjectID;isOutput=true;isSecret=true]$userId"

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Vault and Key
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: 'keyVault.json'
        deploymentMode: 'Incremental'
        overrideParameters: '-keyVaultName "$(keyVaultName)" -adminObjectID "$(getAdminObjectID.adminObjectID)" -sshPublicKey "generateKey.sshPrivateKey"'

- stage: Deploy_Infra
  displayName: "Deploy Storage Accounts & Linux VM"
  dependsOn: Generate_SSH_Key
  variables:
    SSH_PUBLIC_KEY: $[ stageDependencies.Generate_SSH_Key.GenerateKey.outputs['generateKey.sshPublicKey'] ]
  jobs:
  - job: Deploy_Azure_Infra
    displayName: "Deploy ARM Templates"
    steps:

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Storage Accounts
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: 'storageAccounts.json'
        deploymentMode: 'Incremental'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Linux Machine
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: 'myLinuxVM.json'
        deploymentMode: 'Incremental'
        overrideParameters: '-sshPublicKey "$(SSH_PUBLIC_KEY)"'

